services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password # Root Password
      MYSQL_DATABASE: ticketing
    ports:
      - "3307:3306" # Expose MySQL port
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/mysql
      - db-data:/var/lib/mysql
volumes:
  db-data:
